name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: rapport/rapport_modelisation/rapport.tex
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir output
      - uses: docker://pandoc/core:2.9
        with:
          args: >-
            -s comutation-manuscript.tex 
            -f latex 
            -t docx 
            -o output/comutation-manuscript.docx 
            --bibliography reference_files/references.bib 
            --bibliography reference_files/R_citations.bib 
            --bibliography reference_files/additional_citations.bib 
            --csl nature-genetics.csl
      - uses: actions/upload-artifact@master
        with:
          name: manuscript
          path: output
